/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.ingsistemas.ada.panaderia.vista;

import co.edu.usbbog.ingsistemas.ada.panaderia.controlador.logica.Gestion_Producto;

/**
 *
 * @author COMPURED
 */
public class PanelPrincipal extends javax.swing.JPanel {
    
    PanelReportes pr;
    PanelGestion pg;
    Gestion_Producto gp;
    Ventana v;


    public PanelPrincipal(Ventana v) {
        this.v =v;
        this.gp = v.getGp(); 
        this.pr = v.getPr();
        this.pg = v.getPg();
        v.getGp().actualizarLista();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(740, 500));
        setMinimumSize(new java.awt.Dimension(740, 500));
        setPreferredSize(new java.awt.Dimension(740, 500));
        setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\panaderiaProyecto\\src\\co\\edu\\usbbog\\ingsistemas\\ada\\panaderia\\vista\\imagenes\\logo.png")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(230, 50, 290, 290);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonOFF.png"))); // NOI18N
        jButton1.setText("VENTAS");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonSELECT.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(130, 363, 244, 33);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonOFF.png"))); // NOI18N
        jButton2.setText("REPORTES");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonSELECT.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(380, 360, 244, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/wallpaper.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        entrarVentas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        entrarReportes();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void entrarVentas() {
        this.setVisible(false);
        v.setVisible(false);
        v.cambiarTitulo(" - Gestion de ventas");
        v.setSize(744, 532);
        v.add(v.getPg());
        v.setLocationRelativeTo(null);
        v.getPg().limpiarCampos();
        v.getPg().setVisible(true);
        v.setVisible(true);
    }

    private void entrarReportes() {
        this.setVisible(false);
        v.setVisible(false);
        v.cambiarTitulo(" - Reportes de ventas");
        v.setSize(744, 532);
        v.add(v.getPr());
        v.setLocationRelativeTo(null);
        v.getPr().setVisible(true);
        v.setVisible(true);
    }
}
