/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.ingsistemas.ada.panaderia.vista;

import co.edu.usbbog.ingsistemas.ada.panaderia.controlador.logica.Gestion_Producto;
import co.edu.usbbog.ingsistemas.ada.panaderia.modelo.Producto;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author COMPURED
 */
public class PanelGestion extends javax.swing.JPanel {

    PanelReportes pr;
    Gestion_Producto gp;
    Ventana v;
    boolean flag = false;
    String nombreProducto = "";
    Icon mensaje = new ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/miniIcono.png"));

    public PanelGestion(Ventana v) {
        this.v = v;
        this.gp = v.getGp();
        this.pr = v.getPr();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonActualizar = new javax.swing.JButton();
        jButtonAnadir = new javax.swing.JButton();
        jButtonModificarV = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonIrInicio = new javax.swing.JButton();
        jButtonIrReportes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jTextFieldNombreProducto = new javax.swing.JTextField();
        jTextFieldMesFV = new javax.swing.JTextField();
        jTextFieldMarcaProducto = new javax.swing.JTextField();
        jTextFieldValorU = new javax.swing.JTextField();
        jTextFieldCantidad = new javax.swing.JTextField();
        jTextFieldDiaFV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAnioFV = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(740, 500));
        setMinimumSize(new java.awt.Dimension(740, 500));
        setPreferredSize(new java.awt.Dimension(740, 500));
        setLayout(null);

        jButtonActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonActualizar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonOFF.png"))); // NOI18N
        jButtonActualizar.setText("Actualizar Venta");
        jButtonActualizar.setBorderPainted(false);
        jButtonActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonActualizar.setOpaque(false);
        jButtonActualizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonSELECT.png"))); // NOI18N
        jButtonActualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButtonActualizar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        add(jButtonActualizar);
        jButtonActualizar.setBounds(450, 200, 250, 40);

        jButtonAnadir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonAnadir.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAnadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonOFF.png"))); // NOI18N
        jButtonAnadir.setText("Añadir Venta");
        jButtonAnadir.setBorderPainted(false);
        jButtonAnadir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAnadir.setOpaque(false);
        jButtonAnadir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonSELECT.png"))); // NOI18N
        jButtonAnadir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButtonAnadir.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButtonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirActionPerformed(evt);
            }
        });
        add(jButtonAnadir);
        jButtonAnadir.setBounds(50, 340, 250, 40);

        jButtonModificarV.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonModificarV.setForeground(new java.awt.Color(0, 0, 0));
        jButtonModificarV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonOFF.png"))); // NOI18N
        jButtonModificarV.setText("Modificar Venta");
        jButtonModificarV.setBorderPainted(false);
        jButtonModificarV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificarV.setOpaque(false);
        jButtonModificarV.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonSELECT.png"))); // NOI18N
        jButtonModificarV.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButtonModificarV.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButtonModificarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarVActionPerformed(evt);
            }
        });
        add(jButtonModificarV);
        jButtonModificarV.setBounds(450, 160, 250, 40);

        jButtonBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonOFF.png"))); // NOI18N
        jButtonBuscar.setText("Buscar Venta");
        jButtonBuscar.setBorderPainted(false);
        jButtonBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBuscar.setOpaque(false);
        jButtonBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonSELECT.png"))); // NOI18N
        jButtonBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButtonBuscar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        add(jButtonBuscar);
        jButtonBuscar.setBounds(450, 280, 250, 40);

        jButtonEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonOFF.png"))); // NOI18N
        jButtonEliminar.setText("Eliminar Venta");
        jButtonEliminar.setBorderPainted(false);
        jButtonEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEliminar.setOpaque(false);
        jButtonEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonSELECT.png"))); // NOI18N
        jButtonEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButtonEliminar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        add(jButtonEliminar);
        jButtonEliminar.setBounds(450, 240, 250, 40);

        jButtonIrInicio.setForeground(new java.awt.Color(0, 0, 0));
        jButtonIrInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonicono.jpg"))); // NOI18N
        jButtonIrInicio.setBorder(null);
        jButtonIrInicio.setBorderPainted(false);
        jButtonIrInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonIrInicio.setOpaque(false);
        jButtonIrInicio.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botoniconoPressed.jpg"))); // NOI18N
        jButtonIrInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrInicioActionPerformed(evt);
            }
        });
        add(jButtonIrInicio);
        jButtonIrInicio.setBounds(610, 342, 130, 130);

        jButtonIrReportes.setForeground(new java.awt.Color(0, 0, 0));
        jButtonIrReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonOFF.png"))); // NOI18N
        jButtonIrReportes.setText("Reportes");
        jButtonIrReportes.setBorderPainted(false);
        jButtonIrReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonIrReportes.setOpaque(false);
        jButtonIrReportes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonSELECT.png"))); // NOI18N
        jButtonIrReportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButtonIrReportes.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/botonON.png"))); // NOI18N
        jButtonIrReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrReportesActionPerformed(evt);
            }
        });
        add(jButtonIrReportes);
        jButtonIrReportes.setBounds(610, 470, 130, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("OPCIONES");
        add(jLabel6);
        jLabel6.setBounds(510, 100, 125, 29);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("DATOS PRODUCTO");
        add(jLabel5);
        jLabel5.setBounds(60, 70, 225, 29);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre");
        add(jLabel1);
        jLabel1.setBounds(40, 130, 45, 15);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Marca");
        add(jLabel2);
        jLabel2.setBounds(40, 170, 36, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha de Vencimiento (DD/MM/AAAA)");
        add(jLabel3);
        jLabel3.setBounds(40, 200, 210, 15);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Valor Unit.");
        add(jLabel4);
        jLabel4.setBounds(40, 260, 58, 15);

        jLabelCantidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCantidad.setText("Cantidad");
        add(jLabelCantidad);
        jLabelCantidad.setBounds(40, 300, 70, 15);

        jTextFieldNombreProducto.setBackground(new java.awt.Color(187, 232, 213));
        jTextFieldNombreProducto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldNombreProducto.setForeground(new java.awt.Color(0, 0, 0));
        add(jTextFieldNombreProducto);
        jTextFieldNombreProducto.setBounds(130, 130, 187, 23);

        jTextFieldMesFV.setBackground(new java.awt.Color(187, 232, 213));
        jTextFieldMesFV.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldMesFV.setForeground(new java.awt.Color(0, 0, 0));
        add(jTextFieldMesFV);
        jTextFieldMesFV.setBounds(180, 220, 60, 23);

        jTextFieldMarcaProducto.setBackground(new java.awt.Color(187, 232, 213));
        jTextFieldMarcaProducto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldMarcaProducto.setForeground(new java.awt.Color(0, 0, 0));
        add(jTextFieldMarcaProducto);
        jTextFieldMarcaProducto.setBounds(130, 170, 187, 23);

        jTextFieldValorU.setBackground(new java.awt.Color(187, 232, 213));
        jTextFieldValorU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldValorU.setForeground(new java.awt.Color(0, 0, 0));
        add(jTextFieldValorU);
        jTextFieldValorU.setBounds(130, 260, 187, 23);

        jTextFieldCantidad.setBackground(new java.awt.Color(187, 232, 213));
        jTextFieldCantidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldCantidad.setForeground(new java.awt.Color(0, 0, 0));
        add(jTextFieldCantidad);
        jTextFieldCantidad.setBounds(130, 300, 187, 23);

        jTextFieldDiaFV.setBackground(new java.awt.Color(187, 232, 213));
        jTextFieldDiaFV.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldDiaFV.setForeground(new java.awt.Color(0, 0, 0));
        add(jTextFieldDiaFV);
        jTextFieldDiaFV.setBounds(100, 220, 60, 23);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("/");
        add(jLabel8);
        jLabel8.setBounds(230, 220, 41, 20);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("/");
        add(jLabel9);
        jLabel9.setBounds(150, 220, 41, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("$");
        add(jLabel10);
        jLabel10.setBounds(110, 260, 20, 20);

        jTextFieldAnioFV.setBackground(new java.awt.Color(187, 232, 213));
        jTextFieldAnioFV.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldAnioFV.setForeground(new java.awt.Color(0, 0, 0));
        add(jTextFieldAnioFV);
        jTextFieldAnioFV.setBounds(260, 220, 60, 23);
        add(jSeparator1);
        jSeparator1.setBounds(410, 330, 310, 20);
        add(jSeparator2);
        jSeparator2.setBounds(20, 110, 310, 20);
        add(jSeparator3);
        jSeparator3.setBounds(410, 140, 310, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ingsistemas/ada/panaderia/vista/imagenes/wallpaper.jpg"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(0, 0, 740, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIrReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrReportesActionPerformed
        this.setVisible(false);
        v.setVisible(false);
        v.cambiarTitulo(" - Reportes de Ventas");
        v.setSize(744, 532);
        v.add(v.getPr());
        v.setLocationRelativeTo(null);
        v.getPr().setVisible(true);
        v.setVisible(true);
    }//GEN-LAST:event_jButtonIrReportesActionPerformed

    private void jButtonIrInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrInicioActionPerformed
        this.setVisible(false);
        v.setVisible(false);
        v.cambiarTitulo("");
        v.setSize(744, 532);
        v.add(v.getPp());
        v.setLocationRelativeTo(null);
        v.getPp().setVisible(true);
        v.setVisible(true);
    }//GEN-LAST:event_jButtonIrInicioActionPerformed

    private void jButtonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirActionPerformed
        anadirVenta();
    }//GEN-LAST:event_jButtonAnadirActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        eliminarVenta();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        buscarVenta();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonModificarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarVActionPerformed
        modificarVenta();
    }//GEN-LAST:event_jButtonModificarVActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        actualizarVenta();
    }//GEN-LAST:event_jButtonActualizarActionPerformed
    private static String parseFecha(String f) {
        DateFormat hourdateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date fecha = null;
        String d = "";
        try {
            fecha = hourdateFormat.parse(f);
            d = hourdateFormat.format(fecha);
        } catch (ParseException ex) {
            System.out.println("ex" + ex);
        }
        return d;
    }
    
    private String fechaActual() {
        Date date = new Date();
        DateFormat hourdateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        return hourdateFormat.format(date);
    }

    public void limpiarCampos() {
        jTextFieldNombreProducto.setText("");
        jTextFieldMarcaProducto.setText("");
        jTextFieldMesFV.setText("");
        jTextFieldDiaFV.setText("");
        jTextFieldAnioFV.setText("");
        jTextFieldValorU.setText("");
        jTextFieldCantidad.setText("");
    }

    public boolean validarCamposFecha() {
        try {
            int d = Integer.parseInt(jTextFieldDiaFV.getText());
            int m = Integer.parseInt(jTextFieldMesFV.getText());
            int a = Integer.parseInt(jTextFieldAnioFV.getText());
            return (d >= 1 && d <= 31) && (m >= 1 && m <= 12) && (a >= 2020 && a <= 2021);
        } catch (NumberFormatException e) {
            System.err.println(e);
            return false;
        }
    }

    public boolean validarCampos() {
        return !(jTextFieldNombreProducto.getText().equals("") 
                || jTextFieldMarcaProducto.getText().equals("") 
                || jTextFieldDiaFV.getText().equals("") 
                || jTextFieldMesFV.getText().equals("") 
                || jTextFieldAnioFV.getText().equals("") 
                || jTextFieldValorU.getText().equals("") 
                || jTextFieldCantidad.getText().equals(""));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonAnadir;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonIrInicio;
    private javax.swing.JButton jButtonIrReportes;
    private javax.swing.JButton jButtonModificarV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldAnioFV;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldDiaFV;
    private javax.swing.JTextField jTextFieldMarcaProducto;
    private javax.swing.JTextField jTextFieldMesFV;
    private javax.swing.JTextField jTextFieldNombreProducto;
    private javax.swing.JTextField jTextFieldValorU;
    // End of variables declaration//GEN-END:variables

    private void eliminarVenta() {
        String producto = (String) JOptionPane.showInputDialog(this, "Introduzca el nombre del producto a eliminar:", "BAKERY SHOP - Eliminar venta", JOptionPane.INFORMATION_MESSAGE, mensaje, null, "");
        String fecha = fechaActual();
        if (parseFecha(fecha) != "" && producto != null) {
            if (gp.retirarElemento(producto.toUpperCase(), fecha)) {
                JOptionPane.showMessageDialog(this, "SE ELIMINARON LAS VENTAS DEL PRODUCTO ","BAKERY SHOP",JOptionPane.INFORMATION_MESSAGE,mensaje);
                JOptionPane.showMessageDialog(this, "ULTIMA VENTA ELIMINADA:\n"
                        + gp.getpEliminado().impresionConsola(),"BAKERY SHOP",JOptionPane.INFORMATION_MESSAGE,mensaje);
            } else {
                JOptionPane.showMessageDialog(this, "EL NOMBRE DEL PRODUCTO NO SE ASOCIA CON UNA VENTANA REALIZADA HOY","BAKERY SHOP - Mensaje",JOptionPane.INFORMATION_MESSAGE,mensaje);
            }
        } else {
            JOptionPane.showMessageDialog(this, "CONFLICTO CON LOS DATOS INGRESADOS (REVISE EL FORMATO DE LA FECHA Y EL NOMBRE DEL PRODUCTO","BAKERY SHOP - Mensaje",JOptionPane.INFORMATION_MESSAGE,mensaje);
        }
    }

    private void buscarVenta() {

        String producto = (String) JOptionPane.showInputDialog(this, "Introduzca el nombre del producto a buscar: \n"
                + "(Se mostrara el ultimo registro del producto)", "BAKERY SHOP - Buscar venta", JOptionPane.INFORMATION_MESSAGE, mensaje, null, "");
        if (producto != null) {
            Producto p = gp.buscarProducto(producto.toUpperCase());
            if (p != null) {
                JOptionPane.showMessageDialog(this, "Venta\n"
                        + p.impresionConsola(),"BAKERY SHOP",JOptionPane.INFORMATION_MESSAGE,mensaje);
                gp.actualizarLista();
            } else {
                JOptionPane.showMessageDialog(this, "EL NOMBRE DEL PRODUCTO NO SE ASOCIA CON UNA VENTANA REALIZADA HOY","BAKERY SHOP - Mensaje",JOptionPane.INFORMATION_MESSAGE,mensaje);
            }
        } else {
           JOptionPane.showMessageDialog(this, "CAMPO VACIO");
        }
    }

    public void descomponerFecha(String fecha) {
        String[] desc = fecha.split("/");
        jTextFieldDiaFV.setText(desc[0]);
        jTextFieldMesFV.setText(desc[1]);
        jTextFieldAnioFV.setText(desc[2]);
    }

    private void anadirVenta() {
        if (validarCampos()) {
            if (validarCamposFecha()) {
                try {
                    String fecha = jTextFieldDiaFV.getText() + "/" + jTextFieldMesFV.getText()  + "/" + jTextFieldAnioFV.getText() ;
                    Producto pNuevo = new Producto(jTextFieldNombreProducto.getText().toUpperCase(),
                            parseFecha(fecha).toUpperCase(),
                            Double.parseDouble(jTextFieldValorU.getText()),
                            Integer.parseInt(jTextFieldCantidad.getText()),
                            jTextFieldMarcaProducto.getText().toUpperCase(),
                            fechaActual().toUpperCase(),
                            (Double.parseDouble(jTextFieldValorU.getText()) * Integer.parseInt(jTextFieldCantidad.getText())));

                    if (gp.añadirElemento(pNuevo)) {
                        JOptionPane.showMessageDialog(this, "¡VENTA ALMACENADA CON EXITO!\n"
                                + pNuevo.impresionConsola());
                        limpiarCampos();

                    } else {
                        JOptionPane.showMessageDialog(this, "LA VENTA YA SE ENCUENTRA ALMACENADA EN EL SISTEMA");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "REVISE LOS VALORES INGRESADOS EN LAS SIGUIENTES CASILLAS:\n"
                            + "- FECHA DE VENCIMIENTO (RANGO DE FECHAS (01-31/01-12/2020-2021))\n"
                            + "- VALOR UNITARIO\n"
                            + "- CANTIDAD\n"
                            + "---- Solo se admiten valores númericos ----");
                }
            } else {
                JOptionPane.showMessageDialog(this, "VALORES DE LA FECHA DE VENCIMIENTO NO SON VALIDOS");
            }
        } else {
            JOptionPane.showMessageDialog(this, "TODOS LOS CAMPOS DEBEN ESTAR LLENOS");
        }
    }

    private void modificarVenta() {
        String producto =(String) JOptionPane.showInputDialog(this, "Introduzca el nombre del producto a modificar:", "BAKERY SHOP - Modificar venta", JOptionPane.INFORMATION_MESSAGE, mensaje, null, "");
        Producto p = gp.buscarProducto(producto.toUpperCase());
        if (p != null) {
            flag = true;
            nombreProducto = producto.toUpperCase();
            JOptionPane.showMessageDialog(this, "DESPUES DE MODIFICAR LOS DATOS, DE CLICK EN EL BOTON 'Actualizar Venta'","BAKERY SHOP",JOptionPane.INFORMATION_MESSAGE,mensaje);
            jTextFieldNombreProducto.setText(p.getNombre());
            jTextFieldMarcaProducto.setText(p.getMarca());
            descomponerFecha(p.getFechaVencimiento());
            jTextFieldValorU.setText(String.valueOf(p.getCosto()));
            jTextFieldCantidad.setText(String.valueOf(p.getCantidad()));
        } else {
            JOptionPane.showMessageDialog(this, "NO SE ENCONTRARON REGISTROS ASOCIADOS AL PRODUCTO:" + producto.toUpperCase(),"BAKERY SHOP",JOptionPane.INFORMATION_MESSAGE,mensaje);
        }
    }

    private void actualizarVenta() {
        if (flag && nombreProducto != "") {
            if (validarCampos()) {
                try {
                    String fecha = jTextFieldDiaFV.getText() + "/" + jTextFieldMesFV.getText() + "/" + jTextFieldAnioFV.getText();
                    Producto pNuevo = new Producto(jTextFieldNombreProducto.getText().toUpperCase(),
                            parseFecha(fecha).toUpperCase(),
                            Double.parseDouble(jTextFieldValorU.getText()),
                            Integer.parseInt(jTextFieldCantidad.getText()),
                            jTextFieldMarcaProducto.getText().toUpperCase(),
                            fechaActual().toUpperCase(),
                            (Double.parseDouble(jTextFieldValorU.getText()) * Integer.parseInt(jTextFieldCantidad.getText())));
                    if (gp.modificar(pNuevo, nombreProducto)) {
                        JOptionPane.showMessageDialog(this, "PRODUCTO MODIFICADO CON EXITO\n"
                                + pNuevo.impresionConsola(), "BAKERY SHOP", JOptionPane.INFORMATION_MESSAGE, mensaje);
                        limpiarCampos();
                    } else {
                        JOptionPane.showMessageDialog(this, "PROBLEMAS EN LA MODIFICACIÓN DEL PAIS");
                    }
                } catch (NumberFormatException e) {
                                    JOptionPane.showMessageDialog(this, "REVISE LOS VALORES INGRESADOS EN LAS SIGUIENTES CASILLAS:\n"
                        + "- FECHA DE VENCIMIENTO (RANGO DE FECHAS (01-31/01-12/2020-2021))\n"
                        + "- VALOR UNITARIO\n"
                        + "- CANTIDAD\n"
                        + "---- Solo se admiten valores númericos ----","BAKERY SHOP",JOptionPane.INFORMATION_MESSAGE,mensaje);
                }
                flag = false;
                nombreProducto = "";
            } else {
                JOptionPane.showMessageDialog(this, "TODOS LOS CAMPOS DEBEN ESTAR LLENOS","BAKERY SHOP",JOptionPane.INFORMATION_MESSAGE,mensaje);
            }
        } else {
            JOptionPane.showMessageDialog(this, " No se ha realizado la busqueda previa\n para actualizar los datos de la venta","BAKERY SHOP",JOptionPane.INFORMATION_MESSAGE,mensaje);
        }
    }
}
